/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package libreria.vista;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import libreria.constructor.Editorial;
import libreria.persistencia.Conexion;

/**
 *
 * @author Harold
 */
public class GestionarEditorial extends javax.swing.JPanel {

  Conexion con;
  
  DefaultTableModel modeloTabla;
  Editorial editorial;
  
  public GestionarEditorial() {
    con = new Conexion();
    editorial = null;
    
    initComponents();
    
    modeloTabla = (DefaultTableModel) tablaEditorial.getModel();
    cargarTabla();
    botonDinamico();
  }
  
  private void cargarTabla (){
    for (int i = 0; i < tablaEditorial.getRowCount(); i++) {
      modeloTabla.removeRow(i);
      i-=1;
    }
    for ( Editorial editorial : con.editorial.listadoEditoriales()) {
      modeloTabla.addRow( new Object[] { editorial.getId(), editorial.getNombre() } );
    }
  }
  
  private void botonDinamico () {
    if ( editorial == null ) {
      botonAccion.setText("Guardar");
      botonEliminar.setVisible(false);
      botonCancelar.setVisible(false);
    } else {
      botonAccion.setText("Actualizar");
      botonEliminar.setVisible(true);
      botonCancelar.setVisible(true);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    textoNombre = new javax.swing.JTextField();
    botonAccion = new javax.swing.JButton();
    botonEliminar = new javax.swing.JButton();
    botonCancelar = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaEditorial = new javax.swing.JTable();

    setBackground(new java.awt.Color(246, 246, 246));
    setMaximumSize(new java.awt.Dimension(827, 520));
    setMinimumSize(new java.awt.Dimension(827, 520));
    setPreferredSize(new java.awt.Dimension(827, 520));

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Editoriales");

    jPanel1.setBackground(new java.awt.Color(246, 246, 246));
    jPanel1.setMinimumSize(new java.awt.Dimension(467, 142));

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel2.setText("Nombre de la editorial");

    botonAccion.setText("Guardar/ Editar");
    botonAccion.setMaximumSize(new java.awt.Dimension(73, 20));
    botonAccion.setMinimumSize(new java.awt.Dimension(73, 20));
    botonAccion.setPreferredSize(new java.awt.Dimension(73, 20));
    botonAccion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonAccionActionPerformed(evt);
      }
    });

    botonEliminar.setText("Eliminar");
    botonEliminar.setMaximumSize(new java.awt.Dimension(73, 20));
    botonEliminar.setMinimumSize(new java.awt.Dimension(73, 20));
    botonEliminar.setPreferredSize(new java.awt.Dimension(73, 20));
    botonEliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonEliminarActionPerformed(evt);
      }
    });

    botonCancelar.setText("Cancelar");
    botonCancelar.setMaximumSize(new java.awt.Dimension(73, 20));
    botonCancelar.setMinimumSize(new java.awt.Dimension(73, 20));
    botonCancelar.setPreferredSize(new java.awt.Dimension(73, 20));
    botonCancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonCancelarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(textoNombre, javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(botonAccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
          .addComponent(botonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
          .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(botonAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(15, 15, 15))
    );

    tablaEditorial.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Codigo", "Nombre de la editorial"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tablaEditorial.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tablaEditorialMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tablaEditorial);
    if (tablaEditorial.getColumnModel().getColumnCount() > 0) {
      tablaEditorial.getColumnModel().getColumn(0).setResizable(false);
      tablaEditorial.getColumnModel().getColumn(0).setPreferredWidth(10);
      tablaEditorial.getColumnModel().getColumn(1).setResizable(false);
      tablaEditorial.getColumnModel().getColumn(1).setPreferredWidth(600);
    }

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(0, 0, 0)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void botonAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAccionActionPerformed
    if ( textoNombre.getText().trim().length() > 0 ) {
      if ( editorial == null ) {
        con.editorial.guardarEditorial( new Editorial( 0, textoNombre.getText().trim() ) );    
      } else {
        con.editorial.actualizarEditorial(new Editorial( editorial.getId(), textoNombre.getText().trim() ) );  
        tablaEditorial.clearSelection();
        editorial = null;
      }
      textoNombre.setText("");
      cargarTabla();
    } else {
      JOptionPane.showMessageDialog(botonAccion, "Campo vacío!");
    }
    botonDinamico();
  }//GEN-LAST:event_botonAccionActionPerformed

  private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
    editorial = null;
    textoNombre.setText("");
    tablaEditorial.clearSelection();
    botonDinamico();
  }//GEN-LAST:event_botonCancelarActionPerformed

  private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
    if ( JOptionPane.showConfirmDialog(this, "Desea eliminar al autor "+editorial.getNombre(), "",JOptionPane.YES_NO_OPTION ) == 0 ) {
      con.editorial.eliminarEditorial(editorial.getId() );
      editorial = null;
      textoNombre.setText("");
      cargarTabla();
      botonDinamico();
    }
  }//GEN-LAST:event_botonEliminarActionPerformed

  private void tablaEditorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEditorialMouseClicked
    int id = (int) modeloTabla.getValueAt(tablaEditorial.getSelectedRow(), 0);
    Editorial temporal = con.editorial.consultarEditorialPorId(id);
    editorial = new Editorial( temporal.getId(), temporal.getNombre() );
    textoNombre.setText(editorial.getNombre());
    botonDinamico();
  }//GEN-LAST:event_tablaEditorialMouseClicked


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonAccion;
  private javax.swing.JButton botonCancelar;
  private javax.swing.JButton botonEliminar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tablaEditorial;
  private javax.swing.JTextField textoNombre;
  // End of variables declaration//GEN-END:variables
}
