package libreria.vista;

import libreria.constructor.Usuario;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class Principal extends javax.swing.JFrame {

  String usuario;
  
  public Principal( String usuario ) {
    this.usuario = usuario;
    initComponents();
    
    this.CentrarVentana();
    CambiarPanel(new Bienvenida());
  }
  
  private void CentrarVentana (){
    int altoVentana = this.getHeight();
    int altoPantalla = Toolkit.getDefaultToolkit().getScreenSize().height;
    int alto = (altoPantalla/2) - (altoVentana/2);
    
    int anchoVentana = this.getWidth();
    int anchoPantalla = Toolkit.getDefaultToolkit().getScreenSize().width;
    int ancho = (anchoPantalla/2) - (anchoVentana/2);
    
    this.setLocation(ancho, alto);
  }

  private void CambiarPanel ( JPanel panel ) {
    panel.setSize(827, 520);
    panel.setLocation(0, 0);
    
    panelPrincipal.removeAll();
    panelPrincipal.add( panel, BorderLayout.CENTER);
    panelPrincipal.revalidate();
    panelPrincipal.repaint();
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelPrincipal = new javax.swing.JPanel();
    jMenuBar1 = new javax.swing.JMenuBar();
    menuUsuario = new javax.swing.JMenu();
    menuBienvenida = new javax.swing.JMenuItem();
    jSeparator1 = new javax.swing.JPopupMenu.Separator();
    menuSesion = new javax.swing.JMenuItem();
    menuLibros = new javax.swing.JMenu();
    itemAutor = new javax.swing.JMenuItem();
    itemEditorial = new javax.swing.JMenuItem();
    itemLibro = new javax.swing.JMenuItem();
    separadorInventario = new javax.swing.JPopupMenu.Separator();
    itemReporteInventario = new javax.swing.JMenuItem();
    menuVentas = new javax.swing.JMenu();
    itemVentas = new javax.swing.JMenuItem();
    jSeparator2 = new javax.swing.JPopupMenu.Separator();
    itemReporteVenta = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Librería");
    setResizable(false);

    panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
    panelPrincipal.setLayout(panelPrincipalLayout);
    panelPrincipalLayout.setHorizontalGroup(
      panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 827, Short.MAX_VALUE)
    );
    panelPrincipalLayout.setVerticalGroup(
      panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 520, Short.MAX_VALUE)
    );

    menuUsuario.setText("Usuario");

    menuBienvenida.setText("Bienvenida");
    menuBienvenida.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuBienvenidaActionPerformed(evt);
      }
    });
    menuUsuario.add(menuBienvenida);
    menuUsuario.add(jSeparator1);

    menuSesion.setText("Cerrar sesión");
    menuSesion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuSesionActionPerformed(evt);
      }
    });
    menuUsuario.add(menuSesion);

    jMenuBar1.add(menuUsuario);

    menuLibros.setText("Inventario");

    itemAutor.setText("Autores");
    itemAutor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemAutorActionPerformed(evt);
      }
    });
    menuLibros.add(itemAutor);

    itemEditorial.setText("Editoriales");
    itemEditorial.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemEditorialActionPerformed(evt);
      }
    });
    menuLibros.add(itemEditorial);

    itemLibro.setText("Libros");
    itemLibro.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemLibroActionPerformed(evt);
      }
    });
    menuLibros.add(itemLibro);
    menuLibros.add(separadorInventario);

    itemReporteInventario.setText("Reporte");
    itemReporteInventario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemReporteInventarioActionPerformed(evt);
      }
    });
    menuLibros.add(itemReporteInventario);

    jMenuBar1.add(menuLibros);

    menuVentas.setText("Ventas");

    itemVentas.setText("Vender");
    itemVentas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemVentasActionPerformed(evt);
      }
    });
    menuVentas.add(itemVentas);
    menuVentas.add(jSeparator2);

    itemReporteVenta.setText("Reporte");
    itemReporteVenta.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemReporteVentaActionPerformed(evt);
      }
    });
    menuVentas.add(itemReporteVenta);

    jMenuBar1.add(menuVentas);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void menuSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSesionActionPerformed
    int opcion = JOptionPane.showConfirmDialog(rootPane, "¿Desea cerrar sesión?", "Cerrar sesión", JOptionPane.YES_NO_OPTION);
    if ( opcion == 0 ) {
      new Login().setVisible(true);
      this.dispose();
    }
  }//GEN-LAST:event_menuSesionActionPerformed

  private void menuBienvenidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBienvenidaActionPerformed
    CambiarPanel(new Bienvenida());
  }//GEN-LAST:event_menuBienvenidaActionPerformed

  private void itemLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLibroActionPerformed
    CambiarPanel(new GestionarInventario());
  }//GEN-LAST:event_itemLibroActionPerformed

  private void itemVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVentasActionPerformed
    CambiarPanel(new GestionarVenta());
  }//GEN-LAST:event_itemVentasActionPerformed

  private void itemAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAutorActionPerformed
    CambiarPanel(new GestionarAutor());
  }//GEN-LAST:event_itemAutorActionPerformed

  private void itemEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditorialActionPerformed
    CambiarPanel(new GestionarEditorial());
  }//GEN-LAST:event_itemEditorialActionPerformed

  private void itemReporteInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReporteInventarioActionPerformed
    CambiarPanel(new ReporteInventario());
  }//GEN-LAST:event_itemReporteInventarioActionPerformed

  private void itemReporteVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReporteVentaActionPerformed
    CambiarPanel(new ReporteVentas());
  }//GEN-LAST:event_itemReporteVentaActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuItem itemAutor;
  private javax.swing.JMenuItem itemEditorial;
  private javax.swing.JMenuItem itemLibro;
  private javax.swing.JMenuItem itemReporteInventario;
  private javax.swing.JMenuItem itemReporteVenta;
  private javax.swing.JMenuItem itemVentas;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JPopupMenu.Separator jSeparator1;
  private javax.swing.JPopupMenu.Separator jSeparator2;
  private javax.swing.JMenuItem menuBienvenida;
  private javax.swing.JMenu menuLibros;
  private javax.swing.JMenuItem menuSesion;
  private javax.swing.JMenu menuUsuario;
  private javax.swing.JMenu menuVentas;
  private javax.swing.JPanel panelPrincipal;
  private javax.swing.JPopupMenu.Separator separadorInventario;
  // End of variables declaration//GEN-END:variables
}
