/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package libreria.vista;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import libreria.constructor.Producto;
import libreria.persistencia.Conexion;

/**
 *
 * @author Harold
 */
public class ReporteInventario extends javax.swing.JPanel {

  Conexion con;
  DefaultTableModel modeloTabla;
  
  public ReporteInventario() {
    con = new Conexion();
    initComponents();
    modeloTabla = (DefaultTableModel) tablaLibros.getModel();
    cargarTabla();
  }
  
  private void cargarTabla (){
    for (int i = 0; i < tablaLibros.getRowCount(); i++) {
      modeloTabla.removeRow(i);
      i-=1;
    }
    for ( Producto producto : con.producto.listadoProductos()) {
      if ( producto.getCantidad() <= Integer.parseInt(textoCantidad.getText().trim()) ) {
        modeloTabla.addRow( new Object[] {
          producto.getId(),
          producto.getNombre(),
          producto.getEditorial().getNombre(),
          producto.getAutor().getNombre(),
          producto.getAnho(),
          producto.getCantidad(),
          producto.getPrecio()
        });
      }
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel2 = new javax.swing.JLabel();
    textoCantidad = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaLibros = new javax.swing.JTable();

    setBackground(new java.awt.Color(246, 246, 246));
    setMaximumSize(new java.awt.Dimension(827, 520));
    setMinimumSize(new java.awt.Dimension(827, 520));
    setPreferredSize(new java.awt.Dimension(827, 520));

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel2.setText("Pocas existencias - Reporte");

    textoCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    textoCantidad.setText("2");
    textoCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        textoCantidadKeyReleased(evt);
      }
    });

    jLabel1.setText("Ingresa el número de existencias minima que debe tener cáda producto");

    jLabel3.setText("* En la tabla encontraras los productos a los cuales debes comprarle más existencias.");

    tablaLibros.setAutoCreateRowSorter(true);
    tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Id", "Nombre del libro", "Editorial", "Autor", "Fecha de Publicación", "Cantidad", "Precio"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tablaLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    tablaLibros.getTableHeader().setReorderingAllowed(false);
    jScrollPane1.setViewportView(tablaLibros);
    if (tablaLibros.getColumnModel().getColumnCount() > 0) {
      tablaLibros.getColumnModel().getColumn(0).setResizable(false);
      tablaLibros.getColumnModel().getColumn(1).setResizable(false);
      tablaLibros.getColumnModel().getColumn(2).setResizable(false);
      tablaLibros.getColumnModel().getColumn(3).setResizable(false);
      tablaLibros.getColumnModel().getColumn(4).setResizable(false);
      tablaLibros.getColumnModel().getColumn(5).setResizable(false);
      tablaLibros.getColumnModel().getColumn(6).setResizable(false);
    }

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(textoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(jScrollPane1))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(textoCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void textoCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoCantidadKeyReleased
    try {
      if (textoCantidad.getText().trim().equals("")) return;
      Integer.parseInt(textoCantidad.getText().trim());
    } catch ( NumberFormatException e ) {
      JOptionPane.showMessageDialog(this, "Sólo se admiten números enteros");
      textoCantidad.setText("0");
    } finally {
      cargarTabla();
    }
  }//GEN-LAST:event_textoCantidadKeyReleased


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tablaLibros;
  private javax.swing.JTextField textoCantidad;
  // End of variables declaration//GEN-END:variables
}
