package libreria.vista;

import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import libreria.constructor.Producto;
import libreria.constructor.Venta;
import libreria.persistencia.Conexion;

public class ReporteVentas extends javax.swing.JPanel {

  final String hoy = LocalDate.now().toString();
  final String anho = ""+LocalDate.now().getYear();
  
  Conexion con;
  
  DefaultTableModel modeloTabla;
  Venta venta;

  public ReporteVentas() {
    con = new Conexion();
    
    initComponents();
    
    venta = new Venta();
    modeloTabla = (DefaultTableModel) tablaVenta.getModel();
    
    cargarTabla("todo");
  }

  private void cargarTabla ( String filtro ){
    double total = 0;
    
    for (int i = 0; i < tablaVenta.getRowCount(); i++) {
      modeloTabla.removeRow(i);
      i-=1;
    }
    
    switch ( filtro ) {
      case "hoy" :  for ( Venta venta : con.venta.listadoVentas()) {
                      if ( venta.getFechaOrden().equals(hoy) ){
                        total += venta.getCosto();
                        modeloTabla.addRow( new Object[] {
                          venta.getId(),
                          venta.getFechaOrden(),
                          venta.getCosto()
                        });
                      }
                    }
                    textoTotal.setText(""+total);
                    break;
      case "mes" :  for ( Venta venta : con.venta.listadoVentas()) {
                      if ( venta.getFechaOrden().contains(anho+"-"+month()) ){
                        total += venta.getCosto();
                        modeloTabla.addRow( new Object[] {
                          venta.getId(),
                          venta.getFechaOrden(),
                          venta.getCosto()
                        });
                      }
                    }
                    textoTotal.setText(""+total);
                    break;
      case "todo" : for ( Venta venta : con.venta.listadoVentas()) {
                      total += venta.getCosto();
                      modeloTabla.addRow( new Object[] {
                        venta.getId(),
                        venta.getFechaOrden(),
                        venta.getCosto()
                      });
                    }
                    textoTotal.setText(""+total);
                    break;
    }
  }
  
  private String month (){
    String mes = ""+LocalDate.now().getMonthValue();
    if ( mes.length() == 1 ) mes = "0"+mes;
    return mes;
  }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel2 = new javax.swing.JLabel();
    botonMes = new javax.swing.JButton();
    botonTodo = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaVenta = new javax.swing.JTable();
    jLabel3 = new javax.swing.JLabel();
    textoTotal = new javax.swing.JLabel();
    jScrollPane3 = new javax.swing.JScrollPane();
    textoVenta = new javax.swing.JTextArea();
    botonHoy1 = new javax.swing.JButton();

    setBackground(new java.awt.Color(246, 246, 246));
    setMaximumSize(new java.awt.Dimension(827, 520));
    setMinimumSize(new java.awt.Dimension(827, 520));
    setPreferredSize(new java.awt.Dimension(827, 520));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel2.setText("Ventas - Reporte");
    add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 245, 25));

    botonMes.setText("Mes");
    botonMes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonMesActionPerformed(evt);
      }
    });
    add(botonMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

    botonTodo.setText("Todo");
    botonTodo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonTodoActionPerformed(evt);
      }
    });
    add(botonTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 10, -1, -1));

    tablaVenta.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Id", "Fecha de Venta", "Monto"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tablaVenta.getTableHeader().setResizingAllowed(false);
    tablaVenta.getTableHeader().setReorderingAllowed(false);
    tablaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tablaVentaMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tablaVenta);
    if (tablaVenta.getColumnModel().getColumnCount() > 0) {
      tablaVenta.getColumnModel().getColumn(0).setResizable(false);
      tablaVenta.getColumnModel().getColumn(0).setPreferredWidth(50);
      tablaVenta.getColumnModel().getColumn(1).setResizable(false);
      tablaVenta.getColumnModel().getColumn(1).setPreferredWidth(150);
      tablaVenta.getColumnModel().getColumn(2).setResizable(false);
      tablaVenta.getColumnModel().getColumn(2).setPreferredWidth(60);
    }

    add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, 424, 439));

    jLabel3.setText(" Total $");
    add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 486, -1, 23));

    textoTotal.setText("0");
    add(textoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 486, 185, 23));

    jScrollPane3.setMaximumSize(new java.awt.Dimension(365, 440));
    jScrollPane3.setMinimumSize(new java.awt.Dimension(365, 440));

    textoVenta.setEditable(false);
    textoVenta.setColumns(20);
    textoVenta.setRows(5);
    jScrollPane3.setViewportView(textoVenta);

    add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 41, 365, 440));

    botonHoy1.setText("Hoy");
    botonHoy1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonHoy1ActionPerformed(evt);
      }
    });
    add(botonHoy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));
  }// </editor-fold>//GEN-END:initComponents

  private void botonTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTodoActionPerformed
    textoVenta.setText("");
    textoTotal.setText("0.0");
    cargarTabla("todo");
  }//GEN-LAST:event_botonTodoActionPerformed

  private void botonMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMesActionPerformed
    textoVenta.setText("");
    textoTotal.setText("0.0");
    cargarTabla("mes");
  }//GEN-LAST:event_botonMesActionPerformed

  private void tablaVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVentaMouseClicked
    int id = (int) modeloTabla.getValueAt(tablaVenta.getSelectedRow(), 0);
    
    for ( Venta ven : con.venta.listadoVentas()) {
      if ( ven.getId() == id ) venta = ven;
    }
    
    String orden =  "\nN° de orden: #"+venta.getId()+""
                  + "\nFecha: "+venta.getFechaOrden()+""
                  + "\nTotal: "+venta.getCosto();
    for ( Producto pro : venta.getOrden() ) {
      orden +=  "\n\n  "+pro.getNombre()+" X "+pro.getCantidad()+""
              + "\n  Por: "+pro.getEditorial().getNombre()+"\n  De: "+pro.getAutor().getNombre()+""
              + "\n  Monto: "+pro.getPrecio()+"\n----------------------------------";
    }
    
    textoVenta.setText( orden );
  }//GEN-LAST:event_tablaVentaMouseClicked

  private void botonHoy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHoy1ActionPerformed
    textoVenta.setText("");
    textoTotal.setText("0.0");
    cargarTabla("hoy");
  }//GEN-LAST:event_botonHoy1ActionPerformed
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonHoy1;
  private javax.swing.JButton botonMes;
  private javax.swing.JButton botonTodo;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTable tablaVenta;
  private javax.swing.JLabel textoTotal;
  private javax.swing.JTextArea textoVenta;
  // End of variables declaration//GEN-END:variables
}
